version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENV_NAME:-development}
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - WATCHFILES_FORCE_POLLING=true # for Windows